# -*- coding: utf-8 -*-
"""Machin Learning1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1chTIecKGcEWa5ubtO3z8ihqzun3WHgm0
"""

x=[5,3,-1,2,6]
y=[14,6,-5.5,3.5,18]
print(x,y)

X, Y, XiYi ,Xi2=0,0,0,0
n = len(x)
for i in range(n):
  X=X+x[i]
  Y=Y+y[i]
  XiYi= XiYi+x[i]*y[i]
  Xi2=Xi2+x[i]**2
  print(n,X,Y)

